### ISSUE TITLE
yarn start 报错

### ISSUE THREAD

**Issue by chengmanxiang** [now1then/react-web-pro#11]
yarn install
yarn start
报错
$ webpack serve  --color --progress --config build/webpack.dev.js
1% setup initialize[webpack-cli] Invalid configuration object. Object has been i
nitialized using a configuration object that does not match the API schema.
 - configuration has an unknown property '_assetEmittingPreviousFiles'. These pr
operties are valid:
   object { bonjour?, client?, compress?, dev?, firewall?, headers?, historyApiF
allback?, host?, hot?, http2?, https?, injectClient?, injectHot?, liveReload?, o
nAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, openPage?
, overlay?, port?, proxy?, public?, setupExitSignals?, static?, stdin?, transpor
tMode?, useLocalIp? }
error Command failed with exit code 2.

**Comment by zhoulei06** [comment]
> yarn install
> yarn start
> 报错
> $ webpack serve --color --progress --config build/webpack.dev.js
> 1% setup initialize[webpack-cli] Invalid configuration object. Object has been i
> nitialized using a configuration object that does not match the API schema.
> 
> * configuration has an unknown property '_assetEmittingPreviousFiles'. These pr
>   operties are valid:
>   object { bonjour?, client?, compress?, dev?, firewall?, headers?, historyApiF
>   allback?, host?, hot?, http2?, https?, injectClient?, injectHot?, liveReload?, o
>   nAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, openPage?
>   , overlay?, port?, proxy?, public?, setupExitSignals?, static?, stdin?, transpor
>   tMode?, useLocalIp? }
>   error Command failed with exit code 2.

这个问题解决了吗

**Comment by AsaYao** [comment]
同问 我这边也报错了

**Comment by heiyvQAQ** [comment]
我也是

**Comment by now1then** [comment]
已修复，升级webpack相关的版本

**Comment by Sahyid** [comment]
![image](https://user-images.githubusercontent.com/41290317/135825147-15b498f4-1b18-4636-9764-c4cfdd75b16a.png)
大佬，还是报错
